#version: "3.8"
services:
  grafana:
    image: grafana/grafana:11.3.0-ubuntu
    container_name: grafana
    restart: always
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
     - '3000:3000'
    environment:
     - GF_LOG_LEVEL=debug
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,fetzerch-sunandmoon-datasource
    user: '0'
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
