version: '3.8'

services:
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
            - ./config/passwd_file:/mosquitto/passwd_file:ro
        networks:
            - mosquitto
        restart: unless-stopped
        healthcheck:
          test: ["CMD-SHELL", "mosquitto_sub -u mosquitto_user -P mosquitto_pass -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
          interval: 10s
          timeout: 10s
          retries: 6
networks:
    mosquitto:
        name: mosquitto
        driver: bridge
